version: '3.8'
services:
  web:
    build: ./Site
    volumes:
      - ./Site:/var/www/html
    ports:
      - "8080:80"

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Your_password123
      MYSQL_DATABASE: CSC270
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
